name: Doc spellcheck

on:
  pull_request:
    paths:
      - '**.md'
      - '**.txt'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: install aspell
      run: apt-get install aspell
    - name: install pyspelling
      run: pip3 install pyspelling
    - name: spellcheck
      uses: pyspelling -c .github/spellcheck.yaml
