name: Doc spellcheck

on:
  pull_request:
    paths:
      - '**.md'
      - '**.txt'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Spellcheck Action
      uses: UnicornGlobal/spellcheck-github-actions@0.4.0
